/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as FideliteRouteImport } from './routes/fidelite'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtisansRouteImport } from './routes/artisans'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiviTrackingRouteImport } from './routes/suivi.$tracking'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'
import { Route as ArtisansSlugRouteImport } from './routes/artisans.$slug'
import { Route as PaiementCmiOrderIdRouteImport } from './routes/paiement.cmi.$orderId'
import { Route as ApiChatSoukRouteImport } from './routes/api/chat.souk'
import { Route as ApiOgProductSlugRouteImport } from './routes/api/og.product.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const FideliteRoute = FideliteRouteImport.update({
  id: '/fidelite',
  path: '/fidelite',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansRoute = ArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviTrackingRoute = SuiviTrackingRouteImport.update({
  id: '/suivi/$tracking',
  path: '/suivi/$tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProduitsRoute,
} as any)
const ArtisansSlugRoute = ArtisansSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtisansRoute,
} as any)
const PaiementCmiOrderIdRoute = PaiementCmiOrderIdRouteImport.update({
  id: '/paiement/cmi/$orderId',
  path: '/paiement/cmi/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSoukRoute = ApiChatSoukRouteImport.update({
  id: '/api/chat/souk',
  path: '/api/chat/souk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgProductSlugRoute = ApiOgProductSlugRouteImport.update({
  id: '/api/og/product/$slug',
  path: '/api/og/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/panier': typeof PanierRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$slug': typeof ArtisansSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/suivi/$tracking': typeof SuiviTrackingRoute
  '/api/chat/souk': typeof ApiChatSoukRoute
  '/paiement/cmi/$orderId': typeof PaiementCmiOrderIdRoute
  '/api/og/product/$slug': typeof ApiOgProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/panier': typeof PanierRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$slug': typeof ArtisansSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/suivi/$tracking': typeof SuiviTrackingRoute
  '/api/chat/souk': typeof ApiChatSoukRoute
  '/paiement/cmi/$orderId': typeof PaiementCmiOrderIdRoute
  '/api/og/product/$slug': typeof ApiOgProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artisans': typeof ArtisansRouteWithChildren
  '/auth': typeof AuthRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/favoris': typeof FavorisRoute
  '/fidelite': typeof FideliteRoute
  '/panier': typeof PanierRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/artisans/$slug': typeof ArtisansSlugRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/suivi/$tracking': typeof SuiviTrackingRoute
  '/api/chat/souk': typeof ApiChatSoukRoute
  '/paiement/cmi/$orderId': typeof PaiementCmiOrderIdRoute
  '/api/og/product/$slug': typeof ApiOgProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artisans'
    | '/auth'
    | '/commande'
    | '/compte'
    | '/favoris'
    | '/fidelite'
    | '/panier'
    | '/produits'
    | '/sitemap.xml'
    | '/artisans/$slug'
    | '/produits/$slug'
    | '/suivi/$tracking'
    | '/api/chat/souk'
    | '/paiement/cmi/$orderId'
    | '/api/og/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/artisans'
    | '/auth'
    | '/commande'
    | '/compte'
    | '/favoris'
    | '/fidelite'
    | '/panier'
    | '/produits'
    | '/sitemap.xml'
    | '/artisans/$slug'
    | '/produits/$slug'
    | '/suivi/$tracking'
    | '/api/chat/souk'
    | '/paiement/cmi/$orderId'
    | '/api/og/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artisans'
    | '/auth'
    | '/commande'
    | '/compte'
    | '/favoris'
    | '/fidelite'
    | '/panier'
    | '/produits'
    | '/sitemap.xml'
    | '/artisans/$slug'
    | '/produits/$slug'
    | '/suivi/$tracking'
    | '/api/chat/souk'
    | '/paiement/cmi/$orderId'
    | '/api/og/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtisansRoute: typeof ArtisansRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommandeRoute: typeof CommandeRoute
  CompteRoute: typeof CompteRoute
  FavorisRoute: typeof FavorisRoute
  FideliteRoute: typeof FideliteRoute
  PanierRoute: typeof PanierRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuiviTrackingRoute: typeof SuiviTrackingRoute
  ApiChatSoukRoute: typeof ApiChatSoukRoute
  PaiementCmiOrderIdRoute: typeof PaiementCmiOrderIdRoute
  ApiOgProductSlugRoute: typeof ApiOgProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelite': {
      id: '/fidelite'
      path: '/fidelite'
      fullPath: '/fidelite'
      preLoaderRoute: typeof FideliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans': {
      id: '/artisans'
      path: '/artisans'
      fullPath: '/artisans'
      preLoaderRoute: typeof ArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$tracking': {
      id: '/suivi/$tracking'
      path: '/suivi/$tracking'
      fullPath: '/suivi/$tracking'
      preLoaderRoute: typeof SuiviTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/artisans/$slug': {
      id: '/artisans/$slug'
      path: '/$slug'
      fullPath: '/artisans/$slug'
      preLoaderRoute: typeof ArtisansSlugRouteImport
      parentRoute: typeof ArtisansRoute
    }
    '/paiement/cmi/$orderId': {
      id: '/paiement/cmi/$orderId'
      path: '/paiement/cmi/$orderId'
      fullPath: '/paiement/cmi/$orderId'
      preLoaderRoute: typeof PaiementCmiOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/souk': {
      id: '/api/chat/souk'
      path: '/api/chat/souk'
      fullPath: '/api/chat/souk'
      preLoaderRoute: typeof ApiChatSoukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/product/$slug': {
      id: '/api/og/product/$slug'
      path: '/api/og/product/$slug'
      fullPath: '/api/og/product/$slug'
      preLoaderRoute: typeof ApiOgProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArtisansRouteChildren {
  ArtisansSlugRoute: typeof ArtisansSlugRoute
}

const ArtisansRouteChildren: ArtisansRouteChildren = {
  ArtisansSlugRoute: ArtisansSlugRoute,
}

const ArtisansRouteWithChildren = ArtisansRoute._addFileChildren(
  ArtisansRouteChildren,
)

interface ProduitsRouteChildren {
  ProduitsSlugRoute: typeof ProduitsSlugRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsSlugRoute: ProduitsSlugRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtisansRoute: ArtisansRouteWithChildren,
  AuthRoute: AuthRoute,
  CommandeRoute: CommandeRoute,
  CompteRoute: CompteRoute,
  FavorisRoute: FavorisRoute,
  FideliteRoute: FideliteRoute,
  PanierRoute: PanierRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuiviTrackingRoute: SuiviTrackingRoute,
  ApiChatSoukRoute: ApiChatSoukRoute,
  PaiementCmiOrderIdRoute: PaiementCmiOrderIdRoute,
  ApiOgProductSlugRoute: ApiOgProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
